### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by VinceBernardin** [FoxAhead/Civ2-UI-Additions#10]
First, you all are awesome for doing this!  This is my favorite game of all time.  I've hooked my son on it, too, and now trying to do a multiplayer game with him, but struggling.  

I got the following error when I pressed Play: 

Error: ReadProcessMemory: 5

**Comment by FoxAhead** [comment]
Hi!
That has something to do with memory access rights. Error code 5 is ERROR_ACCESS_DENIED. Which probably means that launcher can not read/write memory of created game process. That is strange because in all my test environments all works fine. For now I can not reproduce this error. But I can recommend to try run the launcher "As Administrator". Also check if some antivirus software interferes.

**Comment by VinceBernardin** [comment]
Thanks so much!  I also saw the other thread about not using the fix CPU option with the multiplayer fix and the combination of that and Running as Administrator worked.  

Again, thanks so much!!
